<nav class="navbar navbar-fixed-top" role="navigation">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="showMenu" class="navbar-brand" href="\">Opentherm Gateway</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="status.html">Status</a></li>
                <li><a href="graph.html">Graph</a></li>
                <li><a href="messages.html">Messages</a></li>
                <li><a href="summary.html">Statistics</a></li>
                <li><a href="thermostat.html">Thermostat</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="active"><a href="alert.html">Alert</a></li>
                        <li><a href="clock.html">Clock</a></li>
                        <li><a href="connection.html">Connection</a></li>
                        <li><a href="datalog.html">Datalog</a></li>
                        <li><a href="email.html">Email</a></li>-->
                        <li><a href="upgrade.html">Firmware Upgrade</a></li>
                        <li><a href="mqtt.html">Mqtt</a></li>
                        <li><a href="server.html">Server</a></li>
                        <li><a href="sms.html">Sms</a></li>
                        <li><a href="thinkspeak.html">Thinkspeak</a></li>
                        <li><a href="view.html">View</a></li>
                        <li><a href="web.html">Web</a></li>-->
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Information <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="userpages.html">Custom web pages</a></li>
                        <li><a href="dbus.html">Using DBus</a></li>
                        <li><a href="print.html">Getting gateway settings</a></li>
                        <li><a href="otm_parameters.html">OTMonitor parameters</a></li>
                        <li><a href="attributions.html">Attributions</a></li>
                        <li><a href="http://otgw.tclcode.com/" target="_blank">OTGW Website</a></li>
                        <li><a href="http://www.domoticaforum.eu/viewforum.php?f=75" target="_blank">OTGW Forum domoticaforum.eu</a></li>
                        <li><a href="http://gathering.tweakers.net/forum/list_messages/1653967" target="_blank">OTGW Forum tweakers.net</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dumps <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="json">json</a></li>
                        <li><a href="dashboard.html">Dashboard</a></li>
                        <li><a href="dump_gui.html">Gui</a></li>
                        <li><a href="dump_cfg.html">Cfg</a></li>
                        <li><a href="dump_msg.html">Msg</a></li>
                        <li><a href="dump_error.html">Error</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
