<nav class="navbar navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div id="showMenu" class="navbar-brand"></div>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="dashboard.html">Dashboard</a></li>
                <li><a href="thermostat.html">Thermostat</a></li>
                <li><a href="messages.html">Messages</a></li>
                <li><a href="status.html">Status</a></li>
                <li><a href="summary.html">Statistics</a></li>
                <li><a href="graph.html">Graph</a></li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Configuration<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="cfgthermostat.html">Thermostat</a></li>
                        <li><a href="cfgheater.html">Heater</a></li>
                        <li><a href="cfgleds.html">Leds</a></li>
                        <li><a href="cfgsettings.html">Settings</a></li>
                        <li><a href="cfgcounters.html">Counters</a></li>
                        <li><a href="cfgconnection.html">Connection</a></li>
                        <li><a href="cfglogging.html">Datalog</a></li>
                        <li><a href="cfgalerts.html">Alerts</a></li>
                        <li><a href="cfgwebserver.html">Webserver</a></li>
                        <li><a href="cfgremote.html">Remote</a></li>
                        <li><a href="cfgmqtt.html">MQTT</a></li>
                        <li><a href="cfgtspeak.html">ThinkSpeak</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="alert.html">Alert</a></li>
                        <li><a href="clock.html">Clock</a></li>
                        <li><a href="commands.html">Commands</a></li>
                        <li><a href="email.html">Email</a></li>
                        <li><a href="upgrade.html">Firmware Upgrade</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dumps <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="json">json</a></li>
                        <li><a href="dump_gui.html">Gui</a></li>
                        <li><a href="dump_cfg.html">Cfg</a></li>
                        <li><a href="dump_msg.html">Msg</a></li>
                        <li><a href="dump_error.html">Error</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
